import {
  AlertCircleIcon,
  ArrowRight01Icon,
  Tick01Icon,
  ArrowLeft01Icon,
  ArrowUp01Icon,
  ArrowDown01Icon,
  SquareIcon,
  CreditCardAddIcon,
  File01Icon,
  FileEditIcon,
  HelpCircleIcon,
  Image01Icon,
  ComputerIcon,
  DashboardSpeed01Icon,
  CursorLoading01Icon,
  Login01Icon,
  ShoppingBag01Icon,
  Moon02Icon,
  More01Icon,
  Pizza01Icon,
  Add01Icon,
  Settings02Icon,
  Sun03Icon,
  Delete02Icon,
  NewTwitterIcon,
  UserIcon,
  UserCircleIcon,
  UserEdit01Icon,
  UserRemove01Icon,
  Cancel01Icon,
  PaintBoardIcon,
  GithubIcon,
  Money01Icon,
  DiscountTag01Icon,
  Wallet01Icon,
  Notification01Icon,
  Logout01Icon,
  ImageUpload01Icon,
  Message01Icon
} from 'hugeicons-react';

export type Icon = React.ComponentType<any>;

export const Icons = {
  dashboard: DashboardSpeed01Icon,
  logo: SquareIcon,
  login: Login01Icon,
  close: Cancel01Icon,
  product: ShoppingBag01Icon,
  spinner: CursorLoading01Icon,
  kanban: PaintBoardIcon,
  chevronLeft: ArrowLeft01Icon,
  chevronRight: ArrowRight01Icon,
  trash: Delete02Icon,
  employee: UserRemove01Icon,
  post: FileEditIcon,
  page: File01Icon,
  userPen: UserEdit01Icon,
  user2: UserCircleIcon,
  media: Image01Icon,
  settings: Settings02Icon,
  billing: CreditCardAddIcon,
  ellipsis: More01Icon,
  add: Add01Icon,
  warning: AlertCircleIcon,
  user: UserIcon,
  arrowRight: ArrowRight01Icon,
  help: HelpCircleIcon,
  pizza: Pizza01Icon,
  sun: Sun03Icon,
  moon: Moon02Icon,
  laptop: ComputerIcon,
  github: GithubIcon,
  twitter: NewTwitterIcon,
  check: Tick01Icon,
  receipt: Money01Icon,
  tags: DiscountTag01Icon,
  wallet: Wallet01Icon,
  message: Message01Icon
};
